# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'methods_options.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8


    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)


class Ui_Dialog(QtGui.QDialog):
    def setupUi(self, Dialog):
        QtGui.QDialog.__init__(self)
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(353, 588)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(50, 550, 291, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Ok | QtGui.QDialogButtonBox.Cancel)
        self.buttonBox.button(QtGui.QDialogButtonBox.Ok).setEnabled(False)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.widget = QtGui.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(10, 10, 332, 515))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.widget_2 = QtGui.QWidget(self.widget)
        self.widget_2.setObjectName(_fromUtf8("widget_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.widget_2)
        self.verticalLayout_2.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.bisectionCheckBox = QtGui.QCheckBox(self.widget_2)
        self.bisectionCheckBox.setObjectName(_fromUtf8("bisection"))
        self.verticalLayout_2.addWidget(self.bisectionCheckBox)
        self.verticalLayout.addWidget(self.widget_2)
        self.widget_3 = QtGui.QWidget(self.widget)
        self.widget_3.setObjectName(_fromUtf8("widget_3"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.widget_3)
        self.horizontalLayout_2.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_2 = QtGui.QLabel(self.widget_3)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_2.addWidget(self.label_2)
        self.bisectionXlField = QtGui.QLineEdit(self.widget_3)
        self.bisectionXlField.setObjectName(_fromUtf8("bisectionXlField"))
        self.bisectionXlField.setReadOnly(True)
        self.bisectionXlField.setValidator(QtGui.QDoubleValidator())
        self.horizontalLayout_2.addWidget(self.bisectionXlField)
        self.label = QtGui.QLabel(self.widget_3)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_2.addWidget(self.label)
        self.bisectionXuField = QtGui.QLineEdit(self.widget_3)
        self.bisectionXuField.setObjectName(_fromUtf8("bisectionXuField"))
        self.bisectionXuField.setReadOnly(True)
        self.bisectionXuField.setValidator(QtGui.QDoubleValidator())
        self.horizontalLayout_2.addWidget(self.bisectionXuField)
        self.label.raise_()
        self.bisectionXuField.raise_()
        self.label_2.raise_()
        self.bisectionXlField.raise_()
        self.verticalLayout.addWidget(self.widget_3)
        self.widget_4 = QtGui.QWidget(self.widget)
        self.widget_4.setObjectName(_fromUtf8("widget_4"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.widget_4)
        self.verticalLayout_3.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.falsePositionCheckBox = QtGui.QCheckBox(self.widget_4)
        self.falsePositionCheckBox.setObjectName(_fromUtf8("false_position"))
        self.verticalLayout_3.addWidget(self.falsePositionCheckBox)
        self.verticalLayout.addWidget(self.widget_4)
        self.widget_6 = QtGui.QWidget(self.widget)
        self.widget_6.setObjectName(_fromUtf8("widget_6"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.widget_6)
        self.horizontalLayout.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_4 = QtGui.QLabel(self.widget_6)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout.addWidget(self.label_4)
        self.falsePositionXlField = QtGui.QLineEdit(self.widget_6)
        self.falsePositionXlField.setObjectName(_fromUtf8("falsePositionXlField"))
        self.falsePositionXlField.setReadOnly(True)
        self.falsePositionXlField.setValidator(QtGui.QDoubleValidator())
        self.horizontalLayout.addWidget(self.falsePositionXlField)
        self.label_3 = QtGui.QLabel(self.widget_6)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout.addWidget(self.label_3)
        self.falsePositionXuField = QtGui.QLineEdit(self.widget_6)
        self.falsePositionXuField.setObjectName(_fromUtf8("falsePositionXuField"))
        self.falsePositionXuField.setReadOnly(True)
        self.falsePositionXuField.setValidator(QtGui.QDoubleValidator())
        self.horizontalLayout.addWidget(self.falsePositionXuField)
        self.verticalLayout.addWidget(self.widget_6)
        self.widget_5 = QtGui.QWidget(self.widget)
        self.widget_5.setObjectName(_fromUtf8("widget_5"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.widget_5)
        self.verticalLayout_4.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.fixedPointCheckBox = QtGui.QCheckBox(self.widget_5)
        self.fixedPointCheckBox.setObjectName(_fromUtf8("fixed_point"))
        self.verticalLayout_4.addWidget(self.fixedPointCheckBox)
        self.verticalLayout.addWidget(self.widget_5)
        self.widget_7 = QtGui.QWidget(self.widget)
        self.widget_7.setObjectName(_fromUtf8("widget_7"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.widget_7)
        self.horizontalLayout_3.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_5 = QtGui.QLabel(self.widget_7)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_3.addWidget(self.label_5)
        self.fixedPointX0Field = QtGui.QLineEdit(self.widget_7)
        self.fixedPointX0Field.setObjectName(_fromUtf8("fixedPointX0Field"))
        self.fixedPointX0Field.setReadOnly(True)
        self.fixedPointX0Field.setValidator(QtGui.QDoubleValidator())
        self.horizontalLayout_3.addWidget(self.fixedPointX0Field)
        self.verticalLayout.addWidget(self.widget_7)
        self.widget_9 = QtGui.QWidget(self.widget)
        self.widget_9.setObjectName(_fromUtf8("widget_9"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.widget_9)
        self.verticalLayout_5.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.newtonRaphsonCheckBox = QtGui.QCheckBox(self.widget_9)
        self.newtonRaphsonCheckBox.setObjectName(_fromUtf8("newton_raphson"))
        self.verticalLayout_5.addWidget(self.newtonRaphsonCheckBox)
        self.verticalLayout.addWidget(self.widget_9)
        self.widget_8 = QtGui.QWidget(self.widget)
        self.widget_8.setObjectName(_fromUtf8("widget_8"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.widget_8)
        self.horizontalLayout_4.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_6 = QtGui.QLabel(self.widget_8)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_4.addWidget(self.label_6)
        self.newtonRaphsonX0Field = QtGui.QLineEdit(self.widget_8)
        self.newtonRaphsonX0Field.setObjectName(_fromUtf8("newtonRaphsonX0Field"))
        self.newtonRaphsonX0Field.setReadOnly(True)
        self.newtonRaphsonX0Field.setValidator(QtGui.QDoubleValidator())
        self.horizontalLayout_4.addWidget(self.newtonRaphsonX0Field)
        self.verticalLayout.addWidget(self.widget_8)
        self.widget_13 = QtGui.QWidget(self.widget)
        self.widget_13.setObjectName(_fromUtf8("widget_13"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.widget_13)
        self.verticalLayout_6.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.secantCheckBox = QtGui.QCheckBox(self.widget_13)
        self.secantCheckBox.setObjectName(_fromUtf8("secant"))
        self.verticalLayout_6.addWidget(self.secantCheckBox)
        self.verticalLayout.addWidget(self.widget_13)
        self.widget_10 = QtGui.QWidget(self.widget)
        self.widget_10.setObjectName(_fromUtf8("widget_10"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.widget_10)
        self.horizontalLayout_5.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_8 = QtGui.QLabel(self.widget_10)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_5.addWidget(self.label_8)
        self.secantX0Field = QtGui.QLineEdit(self.widget_10)
        self.secantX0Field.setObjectName(_fromUtf8("secantX0Field"))
        self.secantX0Field.setReadOnly(True)
        self.secantX0Field.setValidator(QtGui.QDoubleValidator())
        self.horizontalLayout_5.addWidget(self.secantX0Field)
        self.label_7 = QtGui.QLabel(self.widget_10)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_5.addWidget(self.label_7)
        self.secantX1Field = QtGui.QLineEdit(self.widget_10)
        self.secantX1Field.setObjectName(_fromUtf8("secantX1Field"))
        self.secantX1Field.setReadOnly(True)
        self.secantX1Field.setValidator(QtGui.QDoubleValidator())
        self.horizontalLayout_5.addWidget(self.secantX1Field)
        self.verticalLayout.addWidget(self.widget_10)
        self.widget_11 = QtGui.QWidget(self.widget)
        self.widget_11.setObjectName(_fromUtf8("widget_11"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.widget_11)
        self.verticalLayout_7.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.birgeVietaCheckBox = QtGui.QCheckBox(self.widget_11)
        self.birgeVietaCheckBox.setObjectName(_fromUtf8("birgeVietaCheckBox"))
        self.verticalLayout_7.addWidget(self.birgeVietaCheckBox)
        self.verticalLayout.addWidget(self.widget_11)
        self.widget_12 = QtGui.QWidget(self.widget)
        self.widget_12.setObjectName(_fromUtf8("widget_12"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.widget_12)
        self.horizontalLayout_6.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_9 = QtGui.QLabel(self.widget_12)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_6.addWidget(self.label_9)
        self.birgeVietaX0Field = QtGui.QLineEdit(self.widget_12)
        self.birgeVietaX0Field.setObjectName(_fromUtf8("birgeVietaX0Field"))
        self.birgeVietaX0Field.setReadOnly(True)
        self.birgeVietaX0Field.setValidator(QtGui.QDoubleValidator())
        self.horizontalLayout_6.addWidget(self.birgeVietaX0Field)
        self.verticalLayout.addWidget(self.widget_12)
        self.widget_14 = QtGui.QWidget(self.widget)
        self.widget_14.setObjectName(_fromUtf8("widget_14"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.widget_14)
        self.verticalLayout_8.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.generalCheckBox = QtGui.QCheckBox(self.widget_14)
        self.generalCheckBox.setObjectName(_fromUtf8("generalCheckBox"))
        self.verticalLayout_8.addWidget(self.generalCheckBox)
        self.verticalLayout.addWidget(self.widget_14)

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.bisectionCheckBox.setText(_translate("Dialog", "Bisection", None))
        self.label_2.setText(_translate("Dialog", "xl", None))
        self.label.setText(_translate("Dialog", "xu", None))
        self.falsePositionCheckBox.setText(_translate("Dialog", "False-Position", None))
        self.label_4.setText(_translate("Dialog", "xl", None))
        self.label_3.setText(_translate("Dialog", "xu", None))
        self.fixedPointCheckBox.setText(_translate("Dialog", "Fixed-Point", None))
        self.label_5.setText(_translate("Dialog", "x0", None))
        self.newtonRaphsonCheckBox.setText(_translate("Dialog", "Newton-Raphson", None))
        self.label_6.setText(_translate("Dialog", "x0", None))
        self.secantCheckBox.setText(_translate("Dialog", "Secant", None))
        self.label_8.setText(_translate("Dialog", "x0", None))
        self.label_7.setText(_translate("Dialog", "x1", None))
        self.birgeVietaCheckBox.setText(_translate("Dialog", "Birge-Vieta", None))
        self.label_9.setText(_translate("Dialog", "x0", None))
        self.generalCheckBox.setText(_translate("Dialog", "General Algorithm", None))


if __name__ == "__main__":
    import sys

    app = QtGui.QApplication(sys.argv)
    Dialog = QtGui.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
